### ISSUE TITLE
Control of TV or other Electronics?

### ISSUE THREAD

**Issue by ToddGreenfield** [flochtililoch/homebridge-lirc-accessory#2]
What type of Accessory are you using to control a TV or Stereo? I see from the lirc-state-api that there is a TV listed, but not a corresponding TV in the accessory. Looking for something to control, Power, Volume, Mute, Input.  Thoughts?

**Comment by flochtililoch** [comment]
[Here's a list of all the services](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L2378-L3229) made avalaible to homebridge (not all of them are available through the iOS Home app FYI).
Unfortunalely, there is no equivalent for TVs, and the Speaker service does not work (last time I checked) on the home app.
I did hook my TV / speakers to home bridge, using a "Switch" accessory, which only allows me to control the power state. [Here's an example of the config I use](https://github.com/flochtililoch/dockers/blob/master/apps/homebridge/homebridge/config.json#L54-L83).
